name: 'Flaky Test Analysis'
description: 'Analyze CI failures and classify flakes using Claude Agent SDK'

inputs:
  repo:
    description: 'Repository to analyze, e.g. my-org/my-repo'
    required: true
  branch:
    description: 'Only analyze runs from this branch. Single name, comma-separated list, or * for all'
    default: 'main'
  lookback-days:
    description: 'How far back to search for failed runs, in days'
    default: '7'
  workflow:
    description: 'Workflow file(s) to analyze (from .github/workflows/). Single name, comma-separated list, or * for all'
    required: true
  skip-jobs:
    description: 'Job names to ignore (comma-separated). Useful for aggregation jobs that do not contain test output'
    default: ''
  context:
    description: 'Free-text hints for the classifier, e.g. test framework details, known infra quirks, job naming conventions'
    default: ''
  model:
    description: 'Claude model to use: sonnet, opus, or haiku'
    default: 'sonnet'
  stale-timeout:
    description: 'Safety limit: if no run finishes for this many minutes, cancel remaining work and report what was completed'
    default: '60'
  max-turns:
    description: 'Safety limit: max LLM round-trips each classifier agent can make before stopping'
    default: '50'
  anthropic_api_key:
    description: 'Anthropic API key (for Claude)'
    required: true
  github_token:
    description: 'GitHub token with actions:read permission on the target repo'
    required: true

outputs:
  report:
    description: 'Path to report.md'
    value: ${{ steps.analyze.outputs.report }}
  results:
    description: 'Path to report.json'
    value: ${{ steps.analyze.outputs.results }}
  status:
    description: 'Run status (ok or no-failures)'
    value: ${{ steps.analyze.outputs.status }}
  summary:
    description: 'Short text summary'
    value: ${{ steps.analyze.outputs.summary }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install flakectl
      shell: bash
      run: pip install ${{ github.action_path }}

    - name: Run analysis
      id: analyze
      shell: bash
      run: |
        set +e
        flakectl run \
          --repo "${{ inputs.repo }}" \
          --branch "${{ inputs.branch }}" \
          --lookback-days "${{ inputs.lookback-days }}" \
          --workflow "${{ inputs.workflow }}" \
          --skip-jobs "${{ inputs.skip-jobs }}" \
          --context "${{ inputs.context }}" \
          --model "${{ inputs.model }}" \
          --stale-timeout "${{ inputs.stale-timeout }}" \
          --max-turns "${{ inputs.max-turns }}"
        RC=$?
        set -e
        if [[ "$RC" -ne 0 && "$RC" -ne 20 ]]; then
          exit "$RC"
        fi
        if [[ "$RC" -eq 20 ]]; then
          echo "status=no-failures" >> "$GITHUB_OUTPUT"
        else
          echo "status=ok" >> "$GITHUB_OUTPUT"
        fi
        echo "report=$PWD/report.md" >> $GITHUB_OUTPUT
        echo "results=$PWD/report.json" >> $GITHUB_OUTPUT
        SUMMARY=$(cat summary.txt 2>/dev/null || echo "Analysis completed. See report.md for details.")
        {
          echo "summary<<EOF"
          echo "$SUMMARY"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        echo "## Flaky Test Report" >> $GITHUB_STEP_SUMMARY
        if [[ -f report.md ]]; then
          cat report.md >> $GITHUB_STEP_SUMMARY
        else
          echo "No report generated." >> $GITHUB_STEP_SUMMARY
        fi
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        GH_TOKEN: ${{ inputs.github_token }}
