"""Tests for flakectl.cli -- simple helpers."""

import json

from flakectl import __version__
from flakectl.cli import (
    _merge_execution_stats,
    _parse_csv_list,
    _resolve_context,
    _write_no_failures_outputs,
)

# ---------------------------------------------------------------------------
# _parse_csv_list
# ---------------------------------------------------------------------------

class TestParseCsvList:
    def test_basic_split(self):
        assert _parse_csv_list("a,b,c") == ["a", "b", "c"]

    def test_spaces_trimmed(self):
        assert _parse_csv_list("a , b , c") == ["a", "b", "c"]

    def test_empty_string(self):
        assert _parse_csv_list("") == []

    def test_trailing_comma(self):
        assert _parse_csv_list("a,b,") == ["a", "b"]


# ---------------------------------------------------------------------------
# _resolve_context
# ---------------------------------------------------------------------------

class TestResolveContext:
    def test_inline_text_returned(self):
        assert _resolve_context("some inline text") == "some inline text"

    def test_at_path_reads_file(self, tmp_path):
        ctx_file = tmp_path / "context.txt"
        ctx_file.write_text("file content here")
        result = _resolve_context(f"@{ctx_file}")
        assert result == "file content here"

    def test_empty_string(self):
        assert _resolve_context("") == ""


# ---------------------------------------------------------------------------
# _write_no_failures_outputs -- AI disclaimer
# ---------------------------------------------------------------------------

class TestNoFailuresDisclaimer:
    def test_no_failures_md_has_disclaimer(self, tmp_path):
        _write_no_failures_outputs(str(tmp_path), "org/repo", "main", "ci.yaml", 7)
        md_text = (tmp_path / "report.md").read_text()
        assert "Always review AI-generated content" in md_text
        assert "> **Note:**" in md_text
        assert "AI-generated by" in md_text

    def test_no_failures_json_has_metadata(self, tmp_path):
        _write_no_failures_outputs(str(tmp_path), "org/repo", "main", "ci.yaml", 7)
        data = json.loads((tmp_path / "report.json").read_text())
        assert "metadata" in data
        assert data["metadata"]["ai_generated"] is True

    def test_no_failures_json_has_version(self, tmp_path):
        _write_no_failures_outputs(str(tmp_path), "org/repo", "main", "ci.yaml", 7)
        data = json.loads((tmp_path / "report.json").read_text())
        assert data["metadata"]["flakectl_version"] == __version__

    def test_no_failures_json_has_model(self, tmp_path):
        _write_no_failures_outputs(
            str(tmp_path), "org/repo", "main", "ci.yaml", 7, model="sonnet",
        )
        data = json.loads((tmp_path / "report.json").read_text())
        assert data["metadata"]["model"] == "sonnet"


# ---------------------------------------------------------------------------
# _merge_execution_stats
# ---------------------------------------------------------------------------

class TestMergeExecutionStats:
    def test_merges_stats_into_report_json(self, tmp_path):
        report = {"metadata": {}, "categories": [], "total_runs": 5}
        path = tmp_path / "report.json"
        path.write_text(json.dumps(report))

        stats = {"model": "sonnet", "classifier_agents": {"count": 3}}
        _merge_execution_stats(str(path), stats)

        data = json.loads(path.read_text())
        assert data["execution_stats"] == stats
        assert data["total_runs"] == 5

    def test_overwrites_existing_stats(self, tmp_path):
        report = {"execution_stats": {"old": True}, "categories": []}
        path = tmp_path / "report.json"
        path.write_text(json.dumps(report))

        stats = {"model": "opus"}
        _merge_execution_stats(str(path), stats)

        data = json.loads(path.read_text())
        assert data["execution_stats"] == {"model": "opus"}
        assert "old" not in data["execution_stats"]
