"""Shared constants for AI transparency and compliance."""

AI_DISCLAIMER = (
    "Always review AI-generated content prior to use. "
    "Classifications, descriptions, and summaries may contain inaccuracies."
)

AI_GENERATED_TAG = "[AI-generated by flakectl]"

USER_GUIDE_URL = "https://github.com/sk-ilya/flakectl/blob/main/docs/USER_GUIDE.md"

FEEDBACK_FORM_URL = "https://forms.gle/BteSPY4zoZoeLcwg9"
